### ISSUE TITLE
Realtime refesh mode

### ISSUE THREAD

**Issue by nishant2019** [pranjal-joshi/Screeni-py#111]
Excellent work done and thanks for sharing the code.Can include a automatic refresh feature where the script updates the data after every fixed time duration given by user

**Comment by pranjal-joshi** [comment]
I didn't understand. Can you explain with am example?

**Comment by nishant2019** [comment]
I have to run screener ever time I want get current  data for my watch list. If a function is built that the the data is automatically refreshed if there are any  trading opportunity without running the commands. Pl see this excel sheet
[https://docs.google.com/spreadsheets/d/1sno4tEwzOZRiepfhoVsBII3wdxdEEjj4OT_7LNm15S4/edit?chrome=false&rm=demo#gid=2068381642](url)

**Comment by pranjal-joshi** [comment]
You can try contributing for the requested by feature by following [these](https://github.com/pranjal-joshi/Screeni-py/blob/main/CONTRIBUTING.md) guidelines.
Otherwise, you can also create a little automation script that loops the watchlist search periodically. :)
