### ISSUE TITLE
Found 0 Stocks, Not getting data in tabuler form

### ISSUE THREAD

**Issue by dixitsutariyaa** [pranjal-joshi/Screeni-py#112]
**Describe the bug**
Found 0 Stocks, there is something wrong with  result = results_queue.get() in **screenipy.py file**, it always returns "None", so variable "**listStockCodes**"  have data but not getting data in tabular format. I am mobile developer by  profession so i tried debugging the code , i found that there is something wrong with **"results_queue = multiprocessing.Queue()"**

* *To Reproduce**

**Expected behavior**
it should display all fetched records to tabular format and push data to excel file

**Screenshots**
![image](https://user-images.githubusercontent.com/25851153/164878415-17fa47dc-8dd6-4aae-9668-10a6e157b4db.png)

**Desktop (please complete the following information):**
 - OS:Win10
 - Browser Mozilla

**Comment by pranjal-joshi** [comment]
Please update to the latest version if not already.
Also, let me know whether it works during market hours / post-market hours because the data source varies as per the current time.
