### ISSUE TITLE
How to change NSE to NASDAQ,NYSE? Basically the USA stock market!

### ISSUE THREAD

**Issue by Acash004** [pranjal-joshi/Screeni-py#121]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pranjal-joshi** [comment]
Hi @Acash004 

Using the same thing for the US stock market is very much possible.

Read about `yfinance` API and replace `.NS` in the following line with appropriate values.
https://github.com/pranjal-joshi/Screeni-py/blob/4d8a65d80ae941cd068c9d3808dd262bbdb36acf/src/classes/Fetcher.py#L113

Please note that you will have to change these data sources for getting stock symbols/codes from the URL of your own stock market.
https://github.com/pranjal-joshi/Screeni-py/blob/4d8a65d80ae941cd068c9d3808dd262bbdb36acf/src/classes/Fetcher.py#L37-L53

Feel free to contribute if you develop any additional features. Happy trading! 📈

**Comment by Acash004** [comment]
Hello, could you please do it for me? Sir, I have no experience and for you, it will only take a few minutes. Please do me a favor, thank you so much. I really want to use this in the [NASDAQ] and the [S&P 500] and all the other stocks in normal stocks trading apps. Please sir, thank you so much!

**Comment by pranjal-joshi** [comment]
@Acash004

**Comment by pranjal-joshi** [comment]
@Acash004 
Hi, I won't be able to implement the changes here as my users are using Screeni-py for NSE India. Changing codes on this branch will break their normal usage.
Please try to implement the changes mentioned above as they're relatively simple. Goodluck!
