### ISSUE TITLE
Custom filters with code

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [pranjal-joshi/Screeni-py#122]
Is it possible to use code to define my own filters using screeni-py ? Couldn't find information about that in the documentation

**Comment by pranjal-joshi** [comment]
@Karlheinzniebuhr 
You can edit the [Screener](https://github.com/pranjal-joshi/Screeni-py/blob/main/src/classes/Screener.py) class to add more methods for your screening.
In case of successful implementation, Please go through [Guidelines for Contribuiting](https://github.com/pranjal-joshi/Screeni-py/blob/new-features/CONTRIBUTING.md) to make your code compatible with the current version before final integration.
