### ISSUE TITLE
screenipy - empty stock list

### ISSUE THREAD

**Issue by pranjal-joshi** [pranjal-joshi/Screeni-py#144]
### Discussed in https://github.com/pranjal-joshi/Screeni-py/discussions/143

<div type='discussions-op-text'>

<sup>Originally posted by **duvvurirao64** December  8, 2022</sup>
after running the screenipy exe file first day i got list of stocks in the table form, but second day onwards showing zero stocks in the table. requesting to help me to solve this problem
thanks in advance
![image](https://user-images.githubusercontent.com/120102901/206442833-7a545858-6c6b-4b30-9bfb-d4faf1b171bc.png)
</div>

**Comment by pranjal-joshi** [comment]
Hi @duvvurirao64

Please try deleting the `screenipy.ini` file from the folder where your `screenipy.exe` is placed. A new `.ini` file will be automatically generated with the default config during the next run.

Requesting you post the screenshot for the following screening:
* Index : (Enter) All Stocks
* Criteria : (2) Screen for stocks with Breakout and volume.

Thanks

**Comment by duvvurirao64** [comment]
its working now thanks sir
