### ISSUE TITLE
Unable to install in MAC - showing illegal hardware in latest version

### ISSUE THREAD

**Issue by mganatra0** [pranjal-joshi/Screeni-py#145]
**Describe the bug**
in the old version I was being able to install and run however in newer version it is showing error of illegal hardware in MAC with M1 chip

**Comment by pranjal-joshi** [comment]
Hi @mganatra0 

The GitHub Actions used to build the executable binary file are still in beta mode for Apple sillicon (M1 & M2).

I recommend you clone the source repo, set up a python environment and run `screenipy.py` script for the time being.
