### ISSUE TITLE
Getting Error While running : WARNING:tensorflow:AutoGraph is not available in this environment

### ISSUE THREAD

**Issue by DINU03** [pranjal-joshi/Screeni-py#152]
When I am trying to try the .exe file in command prompt in windows 10 getting below error message :

WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.
WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.
WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.
WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.
WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.
WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.
WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.

Let me know is this error or bug or normal expected one.

Thanks,
Regards,
Dhinesh

**Comment by pranjal-joshi** [comment]
Do you get the screening options working after warnings?
Or it is stuck only at above warnings?

**Comment by DINU03** [comment]
yes it is working ...

**Comment by theankitsinghpatwal** [comment]
Getting the Same issue but 1 or 2 times then its running
WARNING:tensorflow:AutoGraph is not available in this environment: functions lack code information. This is typical of some environments like the interactive Python shell. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/limitations.md#access-to-source-code for more information.
![Screenshot 2023-01-25 151605](https://user-images.githubusercontent.com/86740417/214530913-c4f340c1-ecb5-4969-b56a-15ac0fb52e1a.png)

**Comment by pranjal-joshi** [comment]
You can safely ignore this warning. The TensorFlow has been packed into binary executable during compile time and is not able to find certain paths while executing on your environment (which is fine)
