### ISSUE TITLE
ERROR !

### ISSUE THREAD

**Issue by srinathra0** [pranjal-joshi/Screeni-py#161]
hey am stuck with this error(mac os) upon double clicking the app

Traceback (most recent call last):
  File "screenipy.py", line 13, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "classes/Screener.py", line 12, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "talib/__init__.py", line 93, in <module>
ImportError: dlopen(/var/folders/_j/yt8t21sn6p1ftcw6158ytxnc0000gn/T/_MEI1EVpWc/talib/_ta_lib.cpython-39-darwin.so, 2): Library not loaded: @loader_path/../libta_lib.0.dylib
  Referenced from: /var/folders/_j/yt8t21sn6p1ftcw6158ytxnc0000gn/T/_MEI1EVpWc/talib/_ta_lib.cpython-39-darwin.so
  Reason: no suitable image found.  Did find:
	/var/folders/_j/yt8t21sn6p1ftcw6158ytxnc0000gn/T/_MEI1EVpWc/talib/../libta_lib.0.dylib: cannot load 'libta_lib.0.dylib' (load command 0x80000034 is unknown)
	/private/var/folders/_j/yt8t21sn6p1ftcw6158ytxnc0000gn/T/_MEI1EVpWc/talib/../libta_lib.0.dylib: cannot load 'libta_lib.0.dylib' (load command 0x80000034 is unknown)
[70529] Failed to execute script 'screenipy' due to unhandled exception: dlopen(/var/folders/_j/yt8t21sn6p1ftcw6158ytxnc0000gn/T/_MEI1EVpWc/talib/_ta_lib.cpython-39-darwin.so, 2): Library not loaded: @loader_path/../libta_lib.0.dylib
  Referenced from: /var/folders/_j/yt8t21sn6p1ftcw6158ytxnc0000gn/T/_MEI1EVpWc/talib/_ta_lib.cpython-39-darwin.so
  Reason: no suitable image found.  Did find:
	/var/folders/_j/yt8t21sn6p1ftcw6158ytxnc0000gn/T/_MEI1EVpWc/talib/../libta_lib.0.dylib: cannot load 'libta_lib.0.dylib' (load command 0x80000034 is unknown)
	/private/var/folders/_j/yt8t21sn6p1ftcw6158ytxnc0000gn/T/_MEI1EVpWc/talib/../libta_lib.0.dylib: cannot load 'libta_lib.0.dylib' (load command 0x80000034 is unknown)
[70529] Traceback:
Traceback (most recent call last):
  File "screenipy.py", line 13, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "classes/Screener.py", line 12, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "talib/__init__.py", line 93, in <module>
ImportError: dlopen(/var/folders/_j/yt8t21sn6p1ftcw6158ytxnc0000gn/T/_MEI1EVpWc/talib/_ta_lib.cpython-39-darwin.so, 2): Library not loaded: @loader_path/../libta_lib.0.dylib
  Referenced from: /var/folders/_j/yt8t21sn6p1ftcw6158ytxnc0000gn/T/_MEI1EVpWc/talib/_ta_lib.cpython-39-darwin.so
  Reason: no suitable image found.  Did find:
	/var/folders/_j/yt8t21sn6p1ftcw6158ytxnc0000gn/T/_MEI1EVpWc/talib/../libta_lib.0.dylib: cannot load 'libta_lib.0.dylib' (load command 0x80000034 is unknown)
	/private/var/folders/_j/yt8t21sn6p1ftcw6158ytxnc0000gn/T/_MEI1EVpWc/talib/../libta_lib.0.dylib: cannot load 'libta_lib.0.dylib' (load command 0x80000034 is unknown)

Regards,
Srinath Rao

**Comment by pranjal-joshi** [comment]
Hi @srinathra0

Please try downloading the latest version.
If the issue persists or you are using Mac with M1/M2 chip, please consider cloning this repo, setup python and dependencies, and the `screenipy.py` rather than using the executable `.run` file.

**Comment by srinathra0** [comment]
hey ! 
sorry for the late reply ..am using pretty old mac (mac book pro 2011) am sort of experimenting with it's work ability as on today! it's (version) indeed i gave it a try with the latest version but still end up with the same error!

**Comment by pranjal-joshi** [comment]
Please clone the code repo and setup your own environment. Build for Mac is having issues due to inconsistent hardware architecture as of now.
