### ISSUE TITLE
# Live Intraday Scanner Issue

### ISSUE THREAD

**Issue by theankitsinghpatwal** [pranjal-joshi/Screeni-py#162]
### Please let me know do you have any discord, telegram group etc.
![Screenshot 2023-02-09 131956](https://user-images.githubusercontent.com/86740417/217750220-d73a5905-4b8c-4558-945c-51d6dee008e7.png)

**Comment by pranjal-joshi** [comment]
Hi @theankitsinghpatwal 

This is not the issue. Please refer to this link #156 to understand how the Live 5-EMA scanner works!

**Comment by theankitsinghpatwal** [comment]
Thanks @pranjal-joshi, i already got the link after 7 min posted the issue or error 
One request from my side that if you make a YouTube video about screeiny.py all feature or detail then might be it will be helpful
Otherwise thanks a lot

**Comment by pranjal-joshi** [comment]
Hi @theankitsinghpatwal 

Here are some points you need to understand:

- Please understand that results won't be displayed after a few minutes.
- Results will be displayed only when the 5-EMA condition will happen in the Nifty or BankNifty. To check these conditions, the scanner is running periodically!
- So some days you may have to wait for a long time while the other days you may get multiple entries. Also, keep in mind that the scanner will not show any previous entries that happened before running the scan option.

**Comment by pranjal-joshi** [comment]
Hi @theankitsinghpatwal 

You can join the telegram group by scanning the QR code available here on the info page: https://github.com/pranjal-joshi/Screeni-py
