### ISSUE TITLE
Facing issue in connection of your github

### ISSUE THREAD

**Issue by praveen0235** [pranjal-joshi/Screeni-py#163]
Am facing the below issue during running the project

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /pranjal-joshi/Screeni-py/actions-data-download/actions-data-download/stock_data_170223.pkl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000028AE1F6AC40>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by pranjal-joshi** [comment]
Hi @praveen0235 

Either GitHub could be down during that period or your ISP is blocking GitHub requests.
Try changing your ISP (Try with a mobile hotspot)
People with JioFiber had faced similar issues earlier.

**Comment by pranjal-joshi** [comment]
Check #91 and #164

**Comment by praveen0235** [comment]
Thank You @pranjal-joshi for the reply.

**Comment by pranjal-joshi** [comment]
Fixed in https://github.com/pranjal-joshi/Screeni-py/issues/164#issuecomment-1754982758
