### ISSUE TITLE
[ConnectionError - HTTPSConnectionPool] Error while scanning any option - Can't reach GitHub domain

### ISSUE THREAD

**Issue by ketulshah84** [pranjal-joshi/Screeni-py#164]
Downloaded latest version - Running on Win10 on Saturday - error faced around 10 PM IST

Tried with Jio Fiber and mobile hotspot (Jio SIM) both.

![image](https://user-images.githubusercontent.com/62036345/219876992-559aa99d-b2ca-4aa6-bc1a-459b329c2ba2.png)

**Comment by pranjal-joshi** [comment]
Please look at #163

**Comment by ketulshah84** [comment]
Tried with Jio Fiber and mobile hotspot (Jio SIM) both.

**Comment by pranjal-joshi** [comment]
Try with something other than the Jio

**Comment by ketulshah84** [comment]
Do you have any alternative solution? Jio is widely used (mobile + Fiber both) by many users.

**Comment by pranjal-joshi** [comment]
If it works on other ISP, you may try raising a ticket regarding this access restriction to the Jio.
Nothing I can do from my end.

**Comment by pranjal-joshi** [comment]
Same as #163 & #91

**Comment by pranjal-joshi** [comment]
## Whoever Facing this ConnectionError ⚠️

Please refer this [**stackoverflow**](https://stackoverflow.com/questions/76292834/jio-blocked-raw-githubusercontent-com#:~:text=Yes%2C%20Jio%20has%20a%20past,URLs%20for%20no%20good%20reason.&text=Reboot%20the%20system%20after%20adding,Otherwise%2C%20reach%20out%20to%20JIO) solution which may help you to fix the ISP issue permanently

**Comment by pranjal-joshi** [comment]
Additional Discussions about JioFiber blocking the domain [raw.githubusercontent.com](raw.githubusercontent.com)
https://github.com/orgs/community/discussions/42655#discussioncomment-4943564

**Comment by pranjal-joshi** [comment]
# Fixed 🎉 
This issue has been finally fixed using 1.1.1.1 Cloudflare DNS.
Please watch the following YouTube video for additional help!
[![https://www.youtube.com/watch?v=JADNADDNTmU](https://markdown-videos-api.jorgenkh.no/url?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DJADNADDNTmU)](https://www.youtube.com/watch?v=JADNADDNTmU)
