### ISSUE TITLE
Can you please give intraday scan for stocks too

### ISSUE THREAD

**Issue by praveen0235** [pranjal-joshi/Screeni-py#166]
Can you please give intraday scan for stocks too

**Comment by pranjal-joshi** [comment]
Hi @praveen0235 

If you are targeting few of the stocks then try `Option > W` (Watchlist) feature of Screeni-py.
Include your favourite stocks in the watchlist and run the scanner in watchlist mode for quick results for any of the available scan criteria.
Hope this helps.

**Comment by praveen0235** [comment]
Hi @pranjal-joshi 

Looking for an intraday scanner for stocks... Watch list will not give us intraday scanning right

**Comment by praveen0235** [comment]
How you are providing for Index in the same way is it possible to give it for stocks too

**Comment by praveen0235** [comment]
Thank You
