### ISSUE TITLE
Inappropriate Signals

### ISSUE THREAD

**Issue by praveen0235** [pranjal-joshi/Screeni-py#167]
Even though the market is bullish today all the intraday signals are related to bearish. And also even though we start the scanning during market hours it is used to print with the previous day's data.

![image](https://user-images.githubusercontent.com/47622775/222129461-cece42e4-3459-4a35-918d-e6eb76f960bd.png)

**Comment by pranjal-joshi** [comment]
Hi @praveen0235 

The market was particularly choppy for the given date. The Author of the 5-EMA strategy themselves have suggested that this strategy often fails in a trending bullish market.

Please notice how the false signals are generated when the candles shown in the white box in the below diagram were forming and not yet closed but crossing the 5-EMA line multiple times. Thus all of the sell signals are triggered due volatility.

<img width="1479" alt="image" src="https://user-images.githubusercontent.com/6128978/222133427-1ac8153f-fdb8-422d-947a-df500fd9df1e.png">

To calculate 5-EMA of 1st candle of the day (9.15 AM), we need to collect at least 5 candles from yesterday's closing. Thus sometimes the false signals for the previous days are observed. Will try to fix that in the next version.

**Comment by praveen0235** [comment]
Hi @pranjal-joshi ,

Really thank you for taking your time and replying back to the concern.

**Request:** Can we consider the candle closing also before generating the signals? Because it gives us somewhat accurate signals.

**Comment by praveen0235** [comment]
Am not part of Dev and am part of the testing domain. If you require any testing activities for this project am open to doing that. Thanks in advance!!!

**Comment by pranjal-joshi** [comment]
Hi @praveen0235 

Already considering the closing price but the API returns the instantaneous price when the candle is not yet closed.
E.g. If the scanner update request runs at 10:13 AM, we will get an instantaneous closing value of candle 10:10 to 10:13 as the candle formation is in progress.

One improvement can be done is verify alert candle colours before giving the signal which will be released in the next version.

**Comment by praveen0235** [comment]
Oh, Great Thank You. Waiting for your next version!!!
