### ISSUE TITLE
Not a bug.. facing some issue .. please help

### ISSUE THREAD

**Issue by tarakbluru** [pranjal-joshi/Screeni-py#168]
![image](https://user-images.githubusercontent.com/1935750/222773666-8dd226c3-dc47-4a75-b26c-08b2880c2288.png)

Can you please take a look and suggest ? I'm trying run from the py files.

thanks.

**Comment by pranjal-joshi** [comment]
Hi @tarakbluru 

You are running the wrong file.
`test/` folder contains the test scripts. It is not standalone executable file.

You need to run `src/screenipy.py` file to run the main application.

**Comment by tarakbluru** [comment]
I had tried that as well. had same issue.. then thought,  I can give test a try..  Here's the screen shot  for screenipy.py
![image](https://user-images.githubusercontent.com/1935750/222781206-80bce604-aaa4-438f-9a26-4b52ddac1d2d.png)

**Comment by pranjal-joshi** [comment]
Have you installed all dependencies in `requirements.txt`?
Please follow the docs to setup the environment

**Comment by tarakbluru** [comment]
Yes.. I did that ..

**Comment by tarakbluru** [comment]
I could proceed with pip install classes

**Comment by tarakbluru** [comment]
facing another issue..
![image](https://user-images.githubusercontent.com/1935750/222790166-13dca437-f99e-450b-b136-920fe6136044.png)

**Comment by pranjal-joshi** [comment]
If you have copy pasted the code it won't work.
Clone the entire repo as the required files are missing in your current folder structure.

It seems like you do not have python expertise so it is recommended to use the exe file for you rather than setting up environments.

If you want to experiment with code, try debugging these basic errors by self research and post only of you're not able to resolve.

**Comment by pranjal-joshi** [comment]
> I could proceed with pip install classes but facing another issue..
> 
> ![image](https://user-images.githubusercontent.com/1935750/222792884-4a64fe72-7d72-41e2-bbb0-5483f019ec36.png)
> 
> Is pip install classes required ? thx.

No @tarakbluru , that is not the correct way.

Please follow section 2 of this docs to setup your environment: https://github.com/pranjal-joshi/Screeni-py/blob/new-features/CONTRIBUTING.md#2-install-project-dependencies

**Comment by tarakbluru** [comment]
I downloaded the from repo ( zip file) and using it. so I do not see the issue of directory structure.  Also, I went through the details in the link that you mentioned.

Only difference is I am using winpython which is portable version of python.

**Comment by pranjal-joshi** [comment]
Hi @tarakbluru 

Without any further error logs, it's not possible to resolve your issue as of now. It just seems like `classes/Fetcher.py` is not inside `src/` folder.

Also, try using a standard version of Python and try debugging the errors.

Let me know if you need additional help with any new error.

**Comment by tarakbluru** [comment]
![image](https://user-images.githubusercontent.com/1935750/222798104-2f2285b0-0ada-46ca-b653-737a08b8165b.png)

My thinking is some how the path of classes subfolder is not getting set/used.   Experimenting with PYTHONPATH ..
