### ISSUE TITLE
Hyperlink not opening

### ISSUE THREAD

**Issue by saktisundar** [pranjal-joshi/Screeni-py#172]
I downloaded the .exe latest file and ran it.
the output is fine but when the tabular column is displayed when clicking on the blue color first column, the graph is not opening.
There is no error message.
I use Windows 10 64-bit system.
Please help out as soon as possible.

**Comment by pranjal-joshi** [comment]
Hi @saktisundar 

Hyperlink does not work on the command prompt of windows as it doesn't support the unicode!
Please use the windows terminal.

For Mac/Linux, it should work on default command lines.

**Comment by saktisundar** [comment]
Thanks. Working fine.
