### ISSUE TITLE
[Bug] Incorrect logic for the "weak down" trend in screener.py:findTrend

### ISSUE THREAD

**Issue by danboyle7** [pranjal-joshi/Screeni-py#173]
**Describe the bug**
There is the findTrend logic error in screening.py.

Under the findTrend function, the logic that labels the trend as "weak down" is incorrect. Currently, it is:
`elif (angle >= -30 and angle < -61):`

However, this case is impossible. It should be:
`elif (angle <= -30 and angle > -61):`

**To Reproduce**
1. Run screenipy on stock with a "weak down" slope below -30 and above -61. 

**Expected behavior**
The screener to correctly classify a trend with an angle between -30 and -61.

**Comment by pranjal-joshi** [comment]
Thanks for reporting the bug @danboyle7 
Will be fixing this in the next release!

**Comment by pranjal-joshi** [comment]
@danboyle7 
Fixed in c30b982
