### ISSUE TITLE
Unknown Result for watchlist stocks

### ISSUE THREAD

**Issue by SammySharma** [pranjal-joshi/Screeni-py#182]
Hi Team,
Thanks for creating such wonderful Application.
While using it for few selected stocks i've found 1 thing which is unknown result. Stock is HDFC which is showing UNKNOWN for many columns. Attached the result output for your reference

![image](https://github.com/pranjal-joshi/Screeni-py/assets/137750522/6e0e88cf-01b6-41b4-a0c1-5b2e813c211e)

**Comment by pranjal-joshi** [comment]
Hi @SammySharma 
Thanks for reporting the issue.
I've checked and found that the Yahoo finance API which screeni-py uses is not returning historical values for HDFC. While it is working properly for rest of the stocks.
<img width="771" alt="image" src="https://github.com/pranjal-joshi/Screeni-py/assets/6128978/eeb28fe5-a6de-4bb9-9b92-16972f1f0d6f">
I hope yfinance will resolve this soon as this is not in my scope.
