### ISSUE TITLE
Question About Nifty Prediction Model

### ISSUE THREAD

**Issue by dopevog** [pranjal-joshi/Screeni-py#186]
Hi @pranjal-joshi, firstly I must say thank you for making such a wonderful tool!

I had some questions about the code actually:
![image](https://github.com/pranjal-joshi/Screeni-py/assets/82938580/5ff7da35-6a62-48c7-b84a-74fc3f44c9d2)
In the image above, could you explain why the code checks if the model files are 1 day old? Does the model change everyday live and is updated on github?

Thanks again,
Dopevog

**Comment by pranjal-joshi** [comment]
The code checks if models are stale. If older than 1 week, it downloads again from GitHub.

As of now there is no CI-CD for ML models but sometimes I update them manually if I get good results with my experiments.
Thus, kept a provision in a code to deliver the same models to users.

This is the most simplest method to update models on the user end.

@dopevog

**Comment by vedantnk9** [comment]
Thanks!

**Comment by dopevog** [comment]
Thanks!
