### ISSUE TITLE
Error for tensorflow on Mac M2

### ISSUE THREAD

**Issue by dopevog** [pranjal-joshi/Screeni-py#187]
Hi @pranjal-joshi, I am using a Macbook pro m2 and am getting the following error while running your code:
![image](https://github.com/pranjal-joshi/Screeni-py/assets/82938580/ef97390c-5a46-471b-9e37-49bc38826339)

Please help me and guide me on what to do!

Thanks,
Dopevog

**Comment by pranjal-joshi** [comment]
@dopevog 

Install `tensorflow-metal` which supports M1/M2 with GPU acceleration

**Comment by dopevog** [comment]
Thanks a lot!

However, now when I run it I am getting the following errors:
![image](https://github.com/pranjal-joshi/Screeni-py/assets/82938580/f9f2651c-c28d-4d34-b483-c37f67dcad04)

**Comment by pranjal-joshi** [comment]
Install required version of pandas as specified in the error
