### ISSUE TITLE
Not giving any Scan results for NIFTY Stocks

### ISSUE THREAD

**Issue by kavyas2912** [pranjal-joshi/Screeni-py#190]
**Describe the bug**
The version 1.43, 1.44 and 1.45 are not scanning any stocks and result is zero stocks

**To Reproduce**
4. See error                                   no error lsited ... just not giving results

**Expected behavior**

on scanning all stocks of Nifty 

**Screenshots**
If applicable, add screenshots to help explain your problem.           not required

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]                                                                                win 11
 - Browser [e.g. chrome, safari]                                                    chrome, edge --latest versions

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.                       request to sort out this glitch

**Comment by pranjal-joshi** [comment]
Please rollback to v1.43 as of now while I fix dependencies in v1.45

**Comment by kavyas2912** [comment]
hi Pranjal

Thanks for response, however same problem with v1.43 as well
pl suggest  how to resolve

thanks buddy, keep it up
wishing you all the best

Regards
K Vyas

**Comment by pranjal-joshi** [comment]
Can you provide screenshot?
Also which OS and OS version you are using?

**Comment by kavyas2912** [comment]
Sure, here it is.

Os - win 11
Desktop.

FYI JUST BEFORE UPDATION BEFORE FEW DAYS, IT WAS WORKING VERY WELL.

**Comment by pranjal-joshi** [comment]
Consider downgrading to the last working version as the root cause of this issue is not yet clear so can't be fixed as of now.

**Comment by Tikam02** [comment]
OS - Ubuntu 20.04
Python - Python3.8

Screeni-py version - V1.43

Not scanning anything, no results on any of the inputs or anything tried everything. 
Please find the screenshot.


![Screenshot from 2023-09-08 15-20-05](https://github.com/pranjal-joshi/Screeni-py/assets/10548085/563ab0fb-1f88-4b12-86df-cb18dd5a3910)

**Comment by pranjal-joshi** [comment]
Try the same for `All stocks` and let me know if it works.
@Tikam02

**Comment by pranjal-joshi** [comment]
I tested just now on the Nifty 500. Worked for me. @Tikam02 
![image](https://github.com/pranjal-joshi/Screeni-py/assets/6128978/cf39971a-1c7d-4690-8926-4eb798823533)

**Comment by kavyas2912** [comment]
while your new version 2.02 is out I am closing the issue for old version.

However, in v2.02, the data fetched is not updated after the first day. 
I usually run "Screenipy" at the end of day to see the scanner results for parameters of all stocks.
Since the data is cached I am unable to see any data update i.e. LTP etc...  it seems the update is not done on server!

it will be good if a time stamp is given for the scanner data fetched / updated.

I use windows 11 Desktop (please complete the following information):

OS: win 11 updated till date.
Browser [e.g. chrome, safari] chrome, edge --latest versions

Thanks buddy... keep up the excellent work

**Comment by kavyas2912** [comment]
thanks ...prices are as per  bhav copy . closing the issue. cheer up. if possible, date time stamp will help
