### ISSUE TITLE
Nifty model doesnt give same accuracy

### ISSUE THREAD

**Issue by dopevog** [pranjal-joshi/Screeni-py#191]
*When I run `experiment.ipynb` the model does not yield the same accuracy as given when the code is first checked*
Before:
![image](https://github.com/pranjal-joshi/Screeni-py/assets/82938580/03423b17-36c8-4b15-a3ab-259156b0104d)
After:
![image](https://github.com/pranjal-joshi/Screeni-py/assets/82938580/5e709619-cec5-490e-8366-3a93bf4990b9)

Could you please help me and explain why this is happening @pranjal-joshi ?

Also, how is the 128 rights and wrongs in the first one when the test size is only 40 days? Also is there way to further backtest the model for more than 40 days (like 100 days)?

**Comment by dopevog** [comment]
Hi it seems that the accuracy given is misleading as maybe you forgot restart the kernel before running the code, so the correct prediction value increased exponentially.

**Comment by pranjal-joshi** [comment]
The ML model training has 3 sub datasets
1. Training
2. Testing
3. Validation

The 100 days results you are watching must be the validation that was neither used for training, nor for testing.

Disclaimer: The training results are experimental and I don't claim whether the accuracy is high enough to take your trading decisions based on it.

**Comment by dopevog** [comment]
Could you say what the test and validation accuracy was for the current model v2?

**Comment by pranjal-joshi** [comment]
No comments on absolute accuracy

Please refer to the notebook shared.
This is the only experiment with ML so far.

**Comment by dopevog** [comment]
Please can you tell me where in the notebook I can find the accuracy?

I understand it is only for educational purposes

**Comment by pranjal-joshi** [comment]
@dopevog 

The following notebook will walk you through data preprocessing, feature engineering, training, validation and testing.

https://github.com/pranjal-joshi/Screeni-py/blob/main/src/ml/experiment.ipynb

**Comment by dopevog** [comment]
@pranjal-joshi could you tell me which cell blocks corespond to which part of the code please? Am facing difficulties trying to find it.

**Comment by dopevog** [comment]
@pranjal-joshi also, is this the same code that was used to make v2 model or was it diffirent?

**Comment by dopevog** [comment]
@pranjal-joshi please respond

**Comment by pranjal-joshi** [comment]
> @pranjal-joshi also, is this the same code that was used to make v2 model or was it diffirent?

The same notebook is updated and used for v2 model

**Comment by pranjal-joshi** [comment]
> @pranjal-joshi could you tell me which cell blocks corespond to which part of the code please? Am facing difficulties trying to find it.

The Jupyter notebooks are self explanatory 😅
I hope you have sufficient python/ML background to get started with this.
If you have specific query, you can refer the piece of code from notebook and then we can discuss.

**Comment by dopevog** [comment]
I am actually pretty new to ML sorry @pranjal-joshi
