### ISSUE TITLE
Momentum Gainers Pattern

### ISSUE THREAD

**Issue by dopevog** [pranjal-joshi/Screeni-py#192]
Hi @pranjal-joshi I really find the Momentum Gainer pattern extremely interesting!
I read your post on it [here](https://github.com/pranjal-joshi/Screeni-py/discussions/95#discussioncomment-1984585).
Could you emphasise a little more and explain how you use it to trade stocks if possible please?

Thanks,
Dopevog

**Comment by pranjal-joshi** [comment]
Continuing this in the same discussion thread as this is not an issue
