### ISSUE TITLE
StockScreen xlsx does not show "updated" LTP etc  for the Current Day

### ISSUE THREAD

**Issue by kavyas2912** [pranjal-joshi/Screeni-py#202]
while your new version 2.02 is out, I used it for last few days and found that the scanner data is not updated.

The data fetched is not updated after the first day.
I usually run "Screenipy" at the end of day to see the scanner results for parameters of "all stocks".
I am unable to see any data update i.e. LTP etc... it seems the update is not done on server!? 

it will be good if a time stamp is given for the scanner data fetched / updated. and loaded in scanner results.

I use windows 11 Desktop (please complete the following information):

OS: win 11 updated till date.
Browser [e.g. chrome, safari] chrome, edge --latest versions

Thanks buddy... keep up the excellent work

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] WIN 11 latest updates
 - Browser [e.g. chrome, safari] Chrome Edge with latest updates

**Comment by kavyas2912** [comment]
sorry the NSE web site and bhavcopy data difference of NSE 50 led me to this.  as per bhav copy its fine. Thanks buddy.

Still time stamp is a good idea.

**Comment by pranjal-joshi** [comment]
Hi @kavyas2912 

The cache is not generated/updated if you screen the stocks during Market Hours i.e. 9 AM to 3.30 PM.

The cache file (.pkl) is only updated if you screen stocks after the market hours.
The server usually creates the cached file around 4-4.30 PM everyday and the timestamp is already appended in the filename.

Here are the logs of action that create the cache everyday for additional information:
https://github.com/pranjal-joshi/Screeni-py/actions/workflows/workflow-download-data.yml
