### ISSUE TITLE
Might not be exactly a bug but seems the amd64 image is missing for latest tag in hub.docker.com

### ISSUE THREAD

**Issue by rahulmr** [pranjal-joshi/Screeni-py#204]
Very nice project.
seems like the amd64 image is missing for latest tag in hub.docker.com
Kindly check it.

**Comment by pranjal-joshi** [comment]
Noted. Thanks.
Triggering the build pipeline manually for this 
https://github.com/pranjal-joshi/Screeni-py/actions/runs/6323627389

**Comment by pranjal-joshi** [comment]
This is now resolved @rahulmr 
<img width="1305" alt="image" src="https://github.com/pranjal-joshi/Screeni-py/assets/6128978/cd700ea7-baac-469d-8aa4-2a0424cbbda0">
