### ISSUE TITLE
Using the app

### ISSUE THREAD

**Issue by akhil-325** [pranjal-joshi/Screeni-py#211]
so i have m1 mac and the app wasnt working. so i downloaded the github file. now how do i run the file?
i am pretty noob. i downloaded the requirements file but cannot figure out.

**Comment by pranjal-joshi** [comment]
YouTube videos are here to help @akhil-325 

https://youtube.com/playlist?list=PLsGnKKT_974J3UVS8M6bxqePfWLeuMsBi&si=C_aAaJwQjjnNHHLF

**Comment by akhil-325** [comment]
thanks
