### ISSUE TITLE
Lorentzian Classifier (Machine Learning based indicator) doesn't work for 7D candle duration

### ISSUE THREAD

**Issue by adityaladwa** [pranjal-joshi/Screeni-py#228]
**Describe the bug**
The Lorentzian Classifier, when used with option 6 as screening criteria and option 7 as type of reversal doesn't give results for 7D candle duration instead returns for 1D candle duration

**To Reproduce**

Select the following configuration 

<img width="1386" alt="Screenshot 2023-12-17 at 5 47 49 PM" src="https://github.com/pranjal-joshi/Screeni-py/assets/4971240/cdeaff7b-fe8e-46f5-82a6-d1410c6a143e">

<img width="1436" alt="Screenshot 2023-12-17 at 5 47 42 PM" src="https://github.com/pranjal-joshi/Screeni-py/assets/4971240/1b0361e7-244a-41c3-aa73-0f51db4dc84e">

**Expected behavior**
The screener should output stocks for the given options using 7D candle duration

**Comment by pranjal-joshi** [comment]
Hi @adityaladwa 
Use duration of `1wk` instead of `7d`
Also increase the period to `3y` or `5y` as you need more historical data as because the timeframe is weekly now
Also, in the second screenshot, I can see 7 results are found.
So please describe the issue with further details if it doesn't work with the configuration suggested above

**Comment by adityaladwa** [comment]
thanks, using `1wk` worked for duration 👍 

>Also, in the second screenshot, I can see 7 results are found.
So please describe the issue with further details if it doesn't work with the configuration suggested above

yes, when using `7D`, I'm still getting same results as for `1D` so raised this issue


Also, is there any reference I can use to understand the configurations in more detail?

**Comment by pranjal-joshi** [comment]
@adityaladwa 

Looks like you're running an older version
The latest version provides drop-downs for configuration attributes so you can choose the valid configuration

**Comment by adityaladwa** [comment]
thank you @pranjal-joshi using latest version now 👍
