### ISSUE TITLE
problem of continuous live  Scanning of  indices - option  of 5 ema scanning in version 1.x

### ISSUE THREAD

**Issue by kavyas2912** [pranjal-joshi/Screeni-py#230]
Hi Pranjal,

Great job buddy.... version 2.x is  good, though ---it needs a large disk overhead. but ok.

Well, for intraday assessment and trading, the option of live scanning of indices -5 EMA - has stopped working in version 1.x.
For intraday Nifty- Banknifty scanning helped a lot till now.... hope you will allow / enable the option. 

Offering continuous scanning of chosen index for few intraday trading criterion viz BB, 5 or10 EMA , SMA-EMA crossover indicators etc will  be a great help. These features are easy for you to add and enable in V2.x 

Overall I am damn happy and grateful to your endeavours. As a retired person, I enjoy fruits of your hard work. Using the Screenipy helps us all in staying unbiased unswayed trading.

wish you all the best 

K Vyas

**Comment by pranjal-joshi** [comment]
Hi @kavyas2912 

Continuous scanning has been deprecated and will not be supported in v2.0 onwards and there is no roadmap to support this as of now.
Looping in the terminal is different and implementing the same in WebApp is bit different.
Please continue using V1 if you're interested in deprecated features
For any other features, use V2
