### ISSUE TITLE
Colab run_screenipy.sh script execution failed 

### ISSUE THREAD

**Issue by Hiddenleaf07** [pranjal-joshi/Screeni-py#235]
https://colab.research.google.com/drive/18M4j6DA8pKSq1fS8tMprBYKhfYM8zXo1

udocker("run -i --entrypoint /bin/bash joshipranjal/screeni-py:latest -c run_screenipy.sh --cli")

**Comment by pranjal-joshi** [comment]
Not sure, the streamlit UI is invoked!
```
You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501/
```

Maybe colab timeout or the kernel is killing it considering it as a blocked thread or some kind of timeout?

**Comment by Hiddenleaf07** [comment]
may be it because Streamlit app create a local network that why it's not working . For Colab it's need localtunnel for used it outside of colab. i didn't have any technical knowledge so will you added localtunnel for Android Support for your screener.

https://colab.research.google.com/github/mrm8488/shared_colab_notebooks/blob/master/Create_streamlit_app.ipynb
