### ISSUE TITLE
F&O Stock Screen Not Work

### ISSUE THREAD

**Issue by raakeshtomarom** [pranjal-joshi/Screeni-py#242]
![Screenshot 2024-07-25 085437](https://github.com/user-attachments/assets/f56dcaf7-5f59-434a-a695-7a922f43271d)
**Describe the bug**
f&O Stock Option Not Work

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pranjal-joshi** [comment]
NSE has changed the data source for their F&O lists. The modified data source currently doesn't allow to obtain the stock lists without a cookie from NSE. This cookie can be obtained from Browser but as of now, I couldn't find a programmatic workaround for this.
The issue will persist till the above solution is obtained.
