### ISSUE TITLE
Stocks screening gets stuck at 660 or 39%

### ISSUE THREAD

**Issue by Napster158** [pranjal-joshi/Screeni-py#58]
When screening all stocks in NSE(1673) after several reruns, the counter is stuck at 660 stocks or 39%.

**To Reproduce**
![Screen Shot 2021-06-12 at 3 59 23 AM](https://user-images.githubusercontent.com/18477812/121754994-a4960d80-cb33-11eb-8cdf-55a7872cb69f.png)

![Screen Shot 2021-06-12 at 4 07 22 AM](https://user-images.githubusercontent.com/18477812/121755029-bbd4fb00-cb33-11eb-8a27-ccf1dea7bdfc.png)

**Comment by pranjal-joshi** [comment]
This issue happening while running compiled `.run` file or you have installed the dependencies and executing the python script?

**Comment by Napster158** [comment]
Hi Pranjal,
I download the source code, installed the dependencies and executed the script.
I ran it again now and observed the same issue, stuck at 660(39%).
![Screen Shot 2021-06-12 at 4 26 30 PM](https://user-images.githubusercontent.com/18477812/121773673-09388300-cb9b-11eb-818b-106365d35251.png)


Option 0 works fine for one scrip at a time.
Can rule out the 2nd possibility if it works fine on your setup, provided we would be hitting the same yahoo fin instance.

**Comment by pranjal-joshi** [comment]
Works fine at my end.

What is your geographical region? I don't know whether Yahoo finance library handles it by different instances by geography or not.

Also monitor the amount of free memory your device having during execution. Check whether it overflows.

Lastly, try using different network than the one you're currently using.

**Comment by Napster158** [comment]
I am based in Bangalore, India. I already checked consumption and available resource, everything is fine on that front.
No worries though, I manually downloaded a list of nifty500 from NSE and created a watchlist to read from so don't need to screen all .
Thank you so much for the follow-up!!

**Comment by pranjal-joshi** [comment]
Good to know that its giving you desired results.

However, if possible, try to switch your network once and run a full screening to ensure that this is not a software issue.

**Comment by pranjal-joshi** [comment]
> Sir, Very Slow Scanning also stuck at 14% 
> 

Please try screening after sometime as the Yahoo finance API may goes under maintenance during the aftermarket hours.

**Comment by pranjal-joshi** [comment]
You can try again with [latest](https://github.com/pranjal-joshi/Screeni-py/releases/latest) version and keep me posted!

**Comment by mhn0497** [comment]
Dear Sir,
I am unable directly open trading view charts by clicking stock name on
windows 10 & 11
Plz send snapshots to install OS/Terminal supports unicode.
Regards,
Mohan

**Comment by pranjal-joshi** [comment]
@mhn0497 Please download `Windows Terminal` from Microsoft store for free and run `screenipy.exe` through Windows terminal to get the Unicode font and clickable TradingView links working.

**Comment by mhn0497** [comment]
Dear Sir,
Thanks for your valuable time to reply, Sir Any Powerful Screener  *only
using ADX Indicator strategy* to find stocks potential breakout probability.
Plz provide any other stock market related screeners if you have.
Regards,
Mohan
