### ISSUE TITLE
Link Broken Not able to download stocks 

### ISSUE THREAD

**Issue by raviyellani** [pranjal-joshi/Screeni-py#65]
![linkbroken](https://user-images.githubusercontent.com/4957036/125555098-dfba43aa-ff9f-4195-8e46-e0a2ed56a515.png)

**Comment by pranjal-joshi** [comment]
Hello,
Currently there is an issue with `yfinance` api. For more information, please go through this [issue](https://github.com/ranaroussi/yfinance/issues/764)
Any contribution to fix this issue will be appreciated!

**Comment by raviyellani** [comment]
Thank your using , on executing below command it worked.

pip install yfinance --upgrade --no-cache-dir

**Comment by pranjal-joshi** [comment]
It's still not working for users who're using HTTP/S Proxy on their machines!
[Link](https://github.com/ranaroussi/yfinance/issues/781) to the issue published at `yfinance`
