### ISSUE TITLE
erro loading

### ISSUE THREAD

**Issue by shashijadhav** [pranjal-joshi/Screeni-py#68]
**Describe the bug
![WhatsApp Image 2021-08-13 at 21 03 02](https://user-images.githubusercontent.com/34806264/129450441-13893861-23f2-4c32-b8b8-032aaa68e014.jpeg)
**
error loading

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pranjal-joshi** [comment]
Hello,
Currently the Screenipy doesn't support Windows 7 as its built for Windows 10.
I recommend you upgrading the OS.
If not possible, use a Virtual Machine with Windows 10 Guest.
