### ISSUE TITLE
Exception at active_bar

### ISSUE THREAD

**Issue by avinayshah** [pranjal-joshi/Screeni-py#72]
**Describe the bug**
Downloaded the latest code and did pip install -r requirements.txt and when running the screenipy.py with any individual stock or group of stock, I see an exception. While debugging I found that while executing **with alive_bar** there seems to be an exception.

`               with alive_bar(numStocks, bar=bar, spinner=spinner) as progressbar:
                    while numStocks:
                        result = results_queue.get()
                        if result is not None:
                            screenResults = screenResults.append(
                                result[0], ignore_index=True)
                            saveResults = saveResults.append(
                                result[1], ignore_index=True)
                        numStocks -= 1
                        progressbar.text(colorText.BOLD + colorText.GREEN +
                                         f'Found {screenResultsCounter.value} Stocks' + colorText.END)
                        progressbar()
            except KeyboardInterrupt:`

**Comment by avinayshah** [comment]
@pranjal-joshi help is appreciated. Thanks in advance.

**Comment by pranjal-joshi** [comment]
> **Describe the bug**
> Downloaded the latest code and did pip install -r requirements.txt and when running the screenipy.py with any individual stock or group of stock, I see an exception. While debugging I found that while executing **with alive_bar** there seems to be an exception.
> 
> `               with alive_bar(numStocks, bar=bar, spinner=spinner) as progressbar:
>                     while numStocks:
>                         result = results_queue.get()
>                         if result is not None:
>                             screenResults = screenResults.append(
>                                 result[0], ignore_index=True)
>                             saveResults = saveResults.append(
>                                 result[1], ignore_index=True)
>                         numStocks -= 1
>                         progressbar.text(colorText.BOLD + colorText.GREEN +
>                                          f'Found {screenResultsCounter.value} Stocks' + colorText.END)
>                         progressbar()
>             except KeyboardInterrupt:`

Please post the exception thrown.

**Comment by avinayshah** [comment]
![image](https://user-images.githubusercontent.com/23154357/133894437-e6b1b816-e01d-4c35-8690-6e4563644503.png)

**Comment by pranjal-joshi** [comment]
Make sure that you've installed it correctly.
Run `pip install alive-progress`.

If the error persist, share the traceback of exception thrown in the terminal.

**Comment by avinayshah** [comment]
I believe it is installed.
![image](https://user-images.githubusercontent.com/23154357/133894596-726b1bf4-e312-4b0d-a16b-291aded5ed17.png)

I commented the **dots_recur** to let it use the **waves** and it seem to not throw the error
![image](https://user-images.githubusercontent.com/23154357/133894624-6205fe5b-30ab-49fe-8db0-a8a7f027c6b5.png)

**Comment by pranjal-joshi** [comment]
Read the alive progress documentation.
Choose the spinner animation that works with your OS.
If you're planning to use it for Screening instead of modifying the features, you can download the `screenipy.exe` from the **Release** section to save the hassle of dependency installation.
