### ISSUE TITLE
not loading after starting stock screening on MAC

### ISSUE THREAD

**Issue by Moxclav** [pranjal-joshi/Screeni-py#76]
application not working after starting stock screening on mac

**Comment by pranjal-joshi** [comment]
Can you try running it through terminal and post the exact error screenshot?

You can go to the directory where `screenipy.run` is downloaded and run following commands.

```
chmod +x screenipy.run
./screenipy.run
```

**Comment by Moxclav** [comment]
i have tried that, however its not going ahead, attached screensho
![Screenshot 2022-01-09 at 3 16 24 PM](https://user-images.githubusercontent.com/97379807/148677264-6203ba1d-6810-44bc-ad14-30dfa84a255e.png)
t

**Comment by Moxclav** [comment]
have tried the same, still not loading, attached screensho
![Screenshot 2022-01-09 at 3 18 06 PM](https://user-images.githubusercontent.com/97379807/148677294-db8231d0-1c92-4ef1-9040-50cd3c317c55.png)
t

**Comment by pranjal-joshi** [comment]
Error printing is disabled in executables.
There must be some dependency issue while building the package.
I recommend you to clone the repo and use the python script rather than .run file as of now till we fix this.
Sorry for the inconvenience!

**Comment by Moxclav** [comment]
okay thanks

**Comment by pranjal-joshi** [comment]
@Moxclav 

Tried fixing this issue with [latest release](https://github.com/pranjal-joshi/Screeni-py/releases/latest).
Please try downloading and testing this `screenipy.run` file on your Mac and update whether it works or not.
