### ISSUE TITLE
Screen for Reversal at Moving Average (Bullish Reversal) - Nothing is Happening

### ISSUE THREAD

**Issue by sunel** [pranjal-joshi/Screeni-py#77]
**Describe the bug**
Selecting Screen for Reversal at Moving Average (Bullish Reversal) does nothinh it just restart the options

**To Reproduce**

Defalut > 6 > 4

**Screenshots**
![image](https://user-images.githubusercontent.com/1009777/148688973-ec320e8c-df1b-4a03-af9c-1d4edfe74fed.png)

**Desktop (please complete the following information):**
 - OS: WINDOWS
 - Version V1.28

**Comment by pranjal-joshi** [comment]
Hello @sunel 

The input provided is wrong.

`MA Length` should be single integer value.
E.g. 20/50 means you can enter any value like 20MA or 50MA.

**How to use?**
Say, if you want to find stocks which is reversing at it's 200MA (Good for long term investment), then you should have following input.

`Enter MA Lenght: 200`

Give it a try and do let me know if the issue still persist.

**Comment by sunel** [comment]
Working

Dispalying somw error will bw useful

**Comment by pranjal-joshi** [comment]
> Working
> 
> Dispalying some error will be useful

Error display will be enabled since next update. Stay Tuned!
