### ISSUE TITLE
Not An issue trying to undertsand the output table

### ISSUE THREAD

**Issue by sunel** [pranjal-joshi/Screeni-py#93]
![image](https://user-images.githubusercontent.com/1009777/149664210-611cb27e-7dd5-4bff-bdc2-732e794d57d2.png)

In the above screenshot what does Range mean

**Comment by pranjal-joshi** [comment]
Hello @sunel 

I have added the section named 'Understanding the Result Table` in 48c6b9.
You can read the documentation [here](https://github.com/pranjal-joshi/Screeni-py/tree/new-features#understanding-the-result-table), It will be merged with main branch in next release.
